name: "Datadog Software Composition Analysis"
description: "Generate SBOM and upload to Datadog"
author: "Datadog"
branding:
  icon: 'check'
  color: 'purple'
inputs:
  dd_api_key:
    description: "Your Datadog API key used to authenticate requests."
    required: true
    default: ""
  dd_app_key:
    description: "Your Datadog Application key used to authenticate requests."
    required: true
    default: ""
  dd_site:
    description: "The Datadog site. For example, users in the EU may want to set datadoghq.eu."
    required: false
    default: "datadoghq.com"
  reachability:
    description: "Enable reachability scanning. Defaults to true."
    required: false
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    DD_API_KEY: ${{ inputs.dd_api_key }}
    DD_APP_KEY: ${{ inputs.dd_app_key }}
    DD_SITE: ${{ inputs.dd_site }}
    REACHABILITY: ${{ inputs.reachability }}
